import type { Metadata } from "next";
import localFont from "next/font/local";

import "./globals.css";
import { ReactQueryProvider } from "./providers/ReactQueryProvider";
import { Suspense } from "react";

const PT_Root = localFont({
  src: [
    {
      path: "../fonts/pt-root-ui_light.woff",
      weight: "400",
      style: "normal",
    },
    {
      path: "../fonts/pt-root-ui_medium.woff",
      weight: "600",
      style: "normal",
    },
    {
      path: "../fonts/pt-root-ui_bold.woff",
      weight: "800",
      style: "normal",
    },
  ],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  viewport: "width=device-width, initial-scale=1.0", // 👈 Добавляем meta viewport
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru">
      <head />
      <body className={PT_Root.className}>
        <ReactQueryProvider>{children}</ReactQueryProvider>
      </body>
    </html>
  );
}
